server:
  port: 8080
spring:
  application:
    name: spring-cloud-nacos-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8849,91.216.169.246:8849  #205 246
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: gateway_service
          uri: lb://spring-cloud-member-service-nacos
          predicates:
            - Path=/**

#server.port: 8080
#spring:
#  application:
#    name: spring-cloud-nacos-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: service1_v1
#          uri: http://localhost:8081/v1
#          predicates:
#            - Path=/**
#            - Weight=service1, 95
#        - id: service1_v2
#          uri: http://localhost:8081/v2
#          predicates:
#            - Path=/**
#            - Weight=service1, 5


